# This is a basic workflow to help you get started with Actions

name: latest
on:
  #push:
    #paths:
     #- 'terraform/*.tfvars'
     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      terraform_apply:
        description: 'Apply terraform changes?'
        required: true
        default: 'false'
        type: boolean 
         
          
 
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  #GITHUB_TOKEN: $({secrets.MY_SECRET})
  #ENVIRONMENT: ${{ github.event.inputs.environment }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Terraform:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu to run the job

    
    steps:
     - name: "setup- code checkout"
       uses: actions/checkout@v3

     - name: "Set up Terraform"
       uses: hashicorp/setup-terraform@v2
       with:
          terraform_version: 1.5.0

     - name: Terraform Init
       run: terraform init
       shell: bash
       
     - name: Terraform Plan
       run:  terraform plan -out=tfplan-nonprod -var-file=non-prod.tfvars
       shell: bash
